services:
  main_server:
    build:
      context: ./main_server
    container_name: main_server
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./main_server/pip_index:/app/pip_index

  lud6:
    build:
      context: ./lud6
      args:
      - JUPYTER_CONFIG_DIR=${JUPYTER_CONFIG_DIR}
    container_name: lud6
    depends_on:
      main_server:
        condition: service_healthy
    environment:
      - PIP_INDEX_URL=${MAIN_HOST}
      - JUPYTER_CONFIG_DIR=${JUPYTER_CONFIG_DIR}
    ports:
      - "8888:8888"
    volumes:
      - ./lud6:/workspace
    working_dir: /workspace
    command: ${JUPYTER_SERVICE_RUN}

  ludf:
    build:
      context: ./ludf
      args:
      - JUPYTER_CONFIG_DIR=${JUPYTER_CONFIG_DIR}
    container_name: ludf
    depends_on:
      main_server:
        condition: service_healthy
    environment:
      - PIP_INDEX_URL=${MAIN_HOST}
      - JUPYTER_CONFIG_DIR=${JUPYTER_CONFIG_DIR}
    ports:
      - "8889:8888"
    volumes:
      - ./ludf:/workspace
    working_dir: /workspace
    command: ${JUPYTER_SERVICE_RUN}
